name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Java files
      run: |
        # Check that Java source files exist and have content
        if [ ! -d "src/ramscoop" ]; then
          echo "Error: Source directory missing"
          exit 1
        fi
        
        if [ ! -f "src/ramscoop/ModPlugin.java" ] || [ ! -f "src/ramscoop/Ramscoop.java" ]; then
          echo "Error: Core Java source files missing"
          exit 1
        fi
        
    - name: Validate mod structure
      run: |
        # Check that essential mod files exist
        for file in "mod_info.json" "settings.json" "README.md"; do
          if [ ! -f "$file" ]; then
            echo "Error: $file is missing"
            exit 1
          fi
        done
        
        # Check that JAR exists
        if [ ! -f "jars/Ramscoop.jar" ]; then
          echo "Warning: Ramscoop.jar is missing, but will be skipped as we can't build it in CI"
        fi
        
    - name: Package validation
      run: |
        # Create a mock release package to ensure the packaging process works
        mkdir -p release
        mkdir -p release/jars
        touch release/jars/Ramscoop.jar
        
        for file in "mod_info.json" "settings.json" "README.md"; do
          cp "$file" release/
        done
        
        cd release
        zip -r "../Ramscoop-test.zip" ./*
        cd ..
        
        # Verify the zip was created and has content
        if [ ! -f "Ramscoop-test.zip" ]; then
          echo "Error: Failed to create test package"
          exit 1
        fi
        
        echo "Package validation successful"
