name: Release Package

on:
  push:
    tags:
      - 'v*' # Trigger on any tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate release files
        run: |
          # Check that essential mod files exist
          for file in "mod_info.json" "settings.json" "README.md" "LICENSE.txt"; do
            if [ ! -f "$file" ]; then
              echo "Error: $file is missing"
              exit 1
            fi
          done
          
          # Verify JAR exists
          if [ ! -f "jars/Ramscoop.jar" ]; then
            echo "Error: Ramscoop.jar is missing"
            exit 1
          fi

      - name: Generate changelog.txt from CHANGELOG.md
        run: |
          # Convert CHANGELOG.md to plain text format for end users
          # Remove markdown formatting and keep the content user-friendly
          sed 's/^## Version /Version /g' CHANGELOG.md | \
          sed 's/^# .*//g' | \
          sed 's/^- /- /g' | \
          sed '/^$/N;/^\n$/d' > changelog.txt
          
          echo "Generated changelog.txt:"
          cat changelog.txt

      - name: Create Release Package
        run: |
          # Create release directory
          mkdir -p release
          
          # Copy only the required files for users
          cp -r jars release/
          cp mod_info.json release/
          cp settings.json release/
          cp README.md release/
          cp LICENSE.txt release/
          cp changelog.txt release/ 2>/dev/null || :
          cp version.json release/ 2>/dev/null || :
          
          # Determine version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Create the zip file
          cd release
          zip -r "../Ramscoop-${VERSION}.zip" ./*
          cd ..

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Ramscoop ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: Ramscoop-${{ github.ref_name }}.zip
          body: |
            # Ramscoop ${{ github.ref_name }}
            
            See the [changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
            
            ## Installation
            
            Extract the zip file into your Starsector/mods directory.
        # Token is automatically used from the GITHUB_TOKEN provided by Actions
